In [1]:
def Hello():
    print 'Hello World!'
    return

Hello()

Hello World!


Python is a simple, high-level scripting language that can be used to build some interesting models in AI. Numpy is a module in Python which has functions for manipulating matrices and performing math operations.
Python是一门主要用于写脚本的高级语言，有很多AI和机器学习的模型是用这个语言搭建的。Numpy则是Python中的一个常用库，其中包含了很多矩阵运算和科学运算的函数与方法。

In [2]:
import numpy
x = numpy.ones((1, 3))
print 'x is ', x

import numpy as np
y = np.zeros_like(x)
print 'y is ', y

#Equivalent
#以上两种语法都正确，我们可以从x的矩阵得到一个跟x一样形状的矩阵y。

x is  [[ 1.  1.  1.]]
y is  [[ 0.  0.  0.]]


In [6]:
#Transpose 对于2D的矩阵而言只是沿着对角翻转
a = np.zeros((3, 2))
print 'a is shaped like ', a.shape
print a
print 'a transpose is shaped like ', a.T.shape
print a.T

a is shaped like  (3L, 2L)
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
a transpose is shaped like  (2L, 3L)
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [7]:
#矩阵可以根据内部的元素做基本加减乘除，这样可以同时处理很多数据，速度更快
a = np.ones((3, 2))
b = np.ones((3, 2)) * 3
#print 'a', a
#print 'b', b

c = a + b
a[2, 1] = 2
d = a * b
print 'c', c
print 'd' , d

c [[ 4.  4.]
 [ 4.  4.]
 [ 4.  4.]]
d [[ 3.  3.]
 [ 3.  3.]
 [ 3.  6.]]


In [ ]:
#Calculates the entropy of the given data set for the target attr
def entropy(attributes, data, targetAttr):

    valFreq = {}
    dataEntropy = 0.0
    
    #find index of the target attribute
    i = 0
    for entry in attributes:
        if (targetAttr == entry):
            break
        ++i
    
    # Calculate the frequency of each of the values in the target attr
    for entry in data:
        if (valFreq.has_key(entry[i])):
            valFreq[entry[i]] += 1.0
        else:
            valFreq[entry[i]]  = 1.0

    # Calculate the entropy of the data for the target attr
    for freq in valFreq.values():
        dataEntropy += (-freq/len(data)) * math.log(freq/len(data), 2) 
        
return dataEntropy


def gain(attributes, data, attr, targetAttr):
    """
    Calculates the information gain (reduction in entropy) that would
    result by splitting the data on the chosen attribute (attr).
    """
    valFreq = {}
    subsetEntropy = 0.0
    
    #find index of the attribute
    i = attributes.index(attr)

    # Calculate the frequency of each of the values in the target attribute
    for entry in data:
        if (valFreq.has_key(entry[i])):
            valFreq[entry[i]] += 1.0
        else:
            valFreq[entry[i]]  = 1.0
    # Calculate the sum of the entropy for each subset of records weighted
    # by their probability of occuring in the training set.
    for val in valFreq.keys():
        valProb        = valFreq[val] / sum(valFreq.values())
        dataSubset     = [entry for entry in data if entry[i] == val]
        subsetEntropy += valProb * entropy(attributes, dataSubset, targetAttr)

    # Subtract the entropy of the chosen attribute from the entropy of the
    # whole data set with respect to the target attribute (and return it)
    return (entropy(attributes, data, targetAttr) - subsetEntropy)
